
image: node:14

prettier:
  script:
    - cd app
    - npm install
    - npm run prettier:check
    - cd ../server
    - npm install
    - npm run prettier:check

eslint:
  script:
    - cd app
    - npm install
    - npm run lint
    - cd ../server
    - npm install
    - npm run lint

backend test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - cd server
    - npm install
    - npm run test:ci
  artifacts:
    reports:
      junit:
        - server/junit.xml
      cobertura: server/coverage/cobertura-coverage.xml
